/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin accounts that can log in and edit website content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload images here (hero photo, instructor photo, etc.), then pick them on the Home Page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short text describing the image — e.g. “Students learning SAP on laptops”.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Everything visitors see on the homepage (srrcareers.com). Open each tab below — changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    badge?: string | null;
    titleLine1?: string | null;
    titleAccent?: string | null;
    primaryCta: {
      label: string;
      /**
       * Page path or URL — e.g. "#courses" or "/courses".
       */
      href: string;
    };
    secondaryCta: {
      label: string;
      /**
       * Page path or URL — e.g. "#courses" or "/courses".
       */
      href: string;
    };
    /**
     * Wide image under the headline. Leave empty to use the default site image.
     */
    image?: (number | null) | Media;
    imageAlt?: string | null;
  };
  problem?: {
    headingGray?: string | null;
    headingNavy?: string | null;
    /**
     * Each row is one concern your visitors might have. Drag to reorder.
     */
    items?:
      | {
          /**
           * Small icon shown above the text.
           */
          icon: 'chat' | 'settings' | 'chart' | 'alert' | 'project' | 'clock';
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  mission?: {
    eyebrow?: string | null;
    headingGray?: string | null;
    headingNavy?: string | null;
    roiCard?: {
      label?: string | null;
      value?: string | null;
      suffix?: string | null;
      description?: string | null;
      partnersLabel?: string | null;
    };
    placementCardTop?: {
      label?: string | null;
      value?: string | null;
      suffix?: string | null;
      description?: string | null;
    };
    alumniCard?: {
      body?: string | null;
      rating?: string | null;
      ratingSuffix?: string | null;
      trustedBy?: string | null;
    };
    placementCardBottom?: {
      label?: string | null;
      value?: string | null;
      suffix?: string | null;
      description?: string | null;
    };
    practiceCard?: {
      label?: string | null;
      value?: string | null;
      description?: string | null;
    };
  };
  instructor?: {
    eyebrow?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    photo?: (number | null) | Media;
    journeyHeading?: string | null;
    journeyBody?: string | null;
    skillsHeading?: string | null;
    skillsBody?: string | null;
    featuresLeft?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    featuresRight?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  curriculum: {
    eyebrow?: string | null;
    titleLine1?: string | null;
    titleLine2?: string | null;
    titleHighlight?: string | null;
    titleLine2Suffix?: string | null;
    /**
     * Number, title, and short description for each row.
     */
    modules?:
      | {
          num: string;
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
    ctaEyebrow?: string | null;
    ctaTitle?: string | null;
    cta: {
      label: string;
      /**
       * Page path or URL — e.g. "#courses" or "/courses".
       */
      href: string;
    };
  };
  testimonials?: {
    eyebrow?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    items?:
      | {
          name: string;
          role: string;
          /**
           * 2 letters shown in the avatar circle — e.g. RS
           */
          initials: string;
          quote: string;
          id?: string | null;
        }[]
      | null;
  };
  preFooter?: {
    badge?: string | null;
    headingLine1?: string | null;
    headingLine2?: string | null;
    description?: string | null;
    /**
     * Display only — phone number itself is in Site Settings (coming soon).
     */
    phoneButtonLabel?: string | null;
    emailButtonLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        titleLine1?: T;
        titleAccent?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
        imageAlt?: T;
      };
  problem?:
    | T
    | {
        headingGray?: T;
        headingNavy?: T;
        items?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
      };
  mission?:
    | T
    | {
        eyebrow?: T;
        headingGray?: T;
        headingNavy?: T;
        roiCard?:
          | T
          | {
              label?: T;
              value?: T;
              suffix?: T;
              description?: T;
              partnersLabel?: T;
            };
        placementCardTop?:
          | T
          | {
              label?: T;
              value?: T;
              suffix?: T;
              description?: T;
            };
        alumniCard?:
          | T
          | {
              body?: T;
              rating?: T;
              ratingSuffix?: T;
              trustedBy?: T;
            };
        placementCardBottom?:
          | T
          | {
              label?: T;
              value?: T;
              suffix?: T;
              description?: T;
            };
        practiceCard?:
          | T
          | {
              label?: T;
              value?: T;
              description?: T;
            };
      };
  instructor?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        photo?: T;
        journeyHeading?: T;
        journeyBody?: T;
        skillsHeading?: T;
        skillsBody?: T;
        featuresLeft?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        featuresRight?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  curriculum?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleLine2?: T;
        titleHighlight?: T;
        titleLine2Suffix?: T;
        modules?:
          | T
          | {
              num?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
        ctaEyebrow?: T;
        ctaTitle?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        items?:
          | T
          | {
              name?: T;
              role?: T;
              initials?: T;
              quote?: T;
              id?: T;
            };
      };
  preFooter?:
    | T
    | {
        badge?: T;
        headingLine1?: T;
        headingLine2?: T;
        description?: T;
        phoneButtonLabel?: T;
        emailButtonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}