/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'course-details': CourseDetail;
    'blog-posts': BlogPost;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'course-details': CourseDetailsSelect<false> | CourseDetailsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'courses-page': CoursesPage;
    'our-story-page': OurStoryPage;
    'whats-new-page': WhatsNewPage;
    'blog-page': BlogPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'courses-page': CoursesPageSelect<false> | CoursesPageSelect<true>;
    'our-story-page': OurStoryPageSelect<false> | OurStoryPageSelect<true>;
    'whats-new-page': WhatsNewPageSelect<false> | WhatsNewPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin accounts that can log in and edit website content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload images here (hero photo, instructor photo, etc.), then pick them on the Home Page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short text describing the image — e.g. “Students learning SAP on laptops”.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Individual course pages at /courses/<slug> (e.g. the Consultant Track and End User Track detail pages). Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-details".
 */
export interface CourseDetail {
  id: number;
  /**
   * Shown in the admin list only.
   */
  name: string;
  /**
   * URL path under /courses/ — e.g. sap-fico-consultant-track.
   */
  slug: string;
  meta: {
    title: string;
    description: string;
  };
  intro: {
    pageTitle: string;
    headline: string;
    headlineHighlight: string;
    subtext?: string | null;
  };
  overview: {
    description: string;
    /**
     * Course fee for checkout.
     */
    price?: number | null;
    originalPrice?: number | null;
    primaryCta?: string | null;
    secondaryCta?: string | null;
    secondaryCtaHref?: string | null;
    moduleCount?: string | null;
    moduleLabel?: string | null;
    moduleBlurb?: string | null;
    metaCards?:
      | {
          icon: 'duration' | 'modules' | 'format' | 'outcome';
          label: string;
          value: string;
          valueSuffix?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  whoIsItFor: {
    eyebrow?: string | null;
    title: string;
    titleHighlight: string;
    audience: string;
    handsOnTitle?: string | null;
    handsOnDescription?: string | null;
    handsOnFeatures: string;
  };
  syllabus?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          /**
           * e.g. "01"
           */
          number: string;
          title: string;
          description?: string | null;
          topics: string;
          id?: string | null;
        }[]
      | null;
  };
  footerBlocks: {
    alsoOffered: {
      eyebrow?: string | null;
      title: string;
      href: string;
      ctaLabel?: string | null;
    };
    limitedSeatsCta?: {
      eyebrow?: string | null;
      titleLine1?: string | null;
      titleLine2?: string | null;
      description?: string | null;
      ctaLabel?: string | null;
      ctaHref?: string | null;
    };
  };
  faq?: {
    eyebrow?: string | null;
    title?: string | null;
    highlight?: string | null;
    helperText?: string | null;
    askLinkLabel?: string | null;
    askLinkHref?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles shown on /blog and /blog/<slug>. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * Shown in the admin list only.
   */
  name: string;
  /**
   * URL path under /blog/ — e.g. sap-fico-career-roadmap.
   */
  slug: string;
  meta: {
    title: string;
    description: string;
  };
  content: {
    title: string;
    /**
     * Shown on cards and at the top of the post.
     */
    excerpt: string;
    /**
     * Optional. Leave empty to use an on-brand gradient banner.
     */
    coverImage?: (number | null) | Media;
    author: string;
    authorRole?: string | null;
    publishedDate: string;
    readTime?: string | null;
    category: string;
    featured?: boolean | null;
    tags?: string | null;
  };
  article?: {
    tableOfContents?: string | null;
    body?:
      | (
          | {
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'paragraph';
            }
          | {
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'heading';
            }
          | {
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'quote';
            }
          | {
              items: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'list';
            }
          | {
              image?: (number | null) | Media;
              caption?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'image';
            }
        )[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'course-details';
        value: number | CourseDetail;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-details_select".
 */
export interface CourseDetailsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        headlineHighlight?: T;
        subtext?: T;
      };
  overview?:
    | T
    | {
        description?: T;
        price?: T;
        originalPrice?: T;
        primaryCta?: T;
        secondaryCta?: T;
        secondaryCtaHref?: T;
        moduleCount?: T;
        moduleLabel?: T;
        moduleBlurb?: T;
        metaCards?:
          | T
          | {
              icon?: T;
              label?: T;
              value?: T;
              valueSuffix?: T;
              id?: T;
            };
      };
  whoIsItFor?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        audience?: T;
        handsOnTitle?: T;
        handsOnDescription?: T;
        handsOnFeatures?: T;
      };
  syllabus?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              topics?: T;
              id?: T;
            };
      };
  footerBlocks?:
    | T
    | {
        alsoOffered?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              href?: T;
              ctaLabel?: T;
            };
        limitedSeatsCta?:
          | T
          | {
              eyebrow?: T;
              titleLine1?: T;
              titleLine2?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        helperText?: T;
        askLinkLabel?: T;
        askLinkHref?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  content?:
    | T
    | {
        title?: T;
        excerpt?: T;
        coverImage?: T;
        author?: T;
        authorRole?: T;
        publishedDate?: T;
        readTime?: T;
        category?: T;
        featured?: T;
        tags?: T;
      };
  article?:
    | T
    | {
        tableOfContents?: T;
        body?:
          | T
          | {
              paragraph?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              heading?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              quote?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              list?:
                | T
                | {
                    items?: T;
                    id?: T;
                    blockName?: T;
                  };
              image?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide chrome shared on every page — header, navigation, footer, contact details, and social links. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand?: {
    /**
     * Shown next to the logo in the header and footer.
     */
    siteName?: string | null;
    footerDescription?: string | null;
    header?: {
      ctaLabel?: string | null;
      ctaHref?: string | null;
    };
  };
  navigation?: {
    items?:
      | {
          label: string;
          href: string;
          badge?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    phone?: string | null;
    /**
     * Leave blank to auto-build from the number.
     */
    phoneHref?: string | null;
    email?: string | null;
    /**
     * Leave blank to auto-build a mailto link.
     */
    emailHref?: string | null;
    whatsappNumber?: string | null;
    whatsappLabel?: string | null;
    whatsappPrefillMessage?: string | null;
  };
  socialGroup?: {
    social?:
      | {
          platform: 'linkedin' | 'instagram' | 'whatsapp';
          label: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    exploreTitle?: string | null;
    exploreLinks?:
      | {
          label: string;
          /**
           * Page path or # anchor or URL
           */
          href: string;
          id?: string | null;
        }[]
      | null;
    courseTitle?: string | null;
    courseLinks?:
      | {
          label: string;
          /**
           * Page path or # anchor or URL
           */
          href: string;
          id?: string | null;
        }[]
      | null;
    contactTitle?: string | null;
    copyright?: string | null;
    craftedText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Everything visitors see on the homepage (srrcareers.com). Open each tab below — changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    badge?: string | null;
    titleLine1?: string | null;
    titleAccent?: string | null;
    primaryCta: {
      label: string;
      /**
       * Page path or URL — e.g. "#courses" or "/courses".
       */
      href: string;
    };
    secondaryCta: {
      label: string;
      /**
       * Page path or URL — e.g. "#courses" or "/courses".
       */
      href: string;
    };
    /**
     * Wide image under the headline. Leave empty to use the default site image.
     */
    image?: (number | null) | Media;
    imageAlt?: string | null;
  };
  problem?: {
    headingGray?: string | null;
    headingNavy?: string | null;
    /**
     * Each row is one concern your visitors might have. Drag to reorder.
     */
    items?:
      | {
          /**
           * Small icon shown above the text.
           */
          icon: 'chat' | 'settings' | 'chart' | 'alert' | 'project' | 'clock';
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  mission?: {
    eyebrow?: string | null;
    headingGray?: string | null;
    headingNavy?: string | null;
    roiCard?: {
      label?: string | null;
      value?: string | null;
      suffix?: string | null;
      description?: string | null;
      partnersLabel?: string | null;
    };
    placementCardTop?: {
      label?: string | null;
      value?: string | null;
      suffix?: string | null;
      description?: string | null;
    };
    alumniCard?: {
      body?: string | null;
      rating?: string | null;
      ratingSuffix?: string | null;
      trustedBy?: string | null;
    };
    placementCardBottom?: {
      label?: string | null;
      value?: string | null;
      suffix?: string | null;
      description?: string | null;
    };
    practiceCard?: {
      label?: string | null;
      value?: string | null;
      description?: string | null;
    };
  };
  instructor?: {
    eyebrow?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    photo?: (number | null) | Media;
    journeyHeading?: string | null;
    journeyBody?: string | null;
    skillsHeading?: string | null;
    skillsBody?: string | null;
    featuresLeft?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    featuresRight?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  curriculum: {
    eyebrow?: string | null;
    titleLine1?: string | null;
    titleLine2?: string | null;
    titleHighlight?: string | null;
    titleLine2Suffix?: string | null;
    /**
     * Number, title, and short description for each row.
     */
    modules?:
      | {
          num: string;
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
    ctaEyebrow?: string | null;
    ctaTitle?: string | null;
    cta: {
      label: string;
      /**
       * Page path or URL — e.g. "#courses" or "/courses".
       */
      href: string;
    };
  };
  testimonials?: {
    eyebrow?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    items?:
      | {
          name: string;
          role: string;
          /**
           * 2 letters shown in the avatar circle — e.g. RS
           */
          initials: string;
          quote: string;
          id?: string | null;
        }[]
      | null;
  };
  preFooter?: {
    badge?: string | null;
    headingLine1?: string | null;
    headingLine2?: string | null;
    description?: string | null;
    /**
     * Display only — phone number itself is in Site Settings (coming soon).
     */
    phoneButtonLabel?: string | null;
    emailButtonLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Courses page (/courses) — intro, the two track cards (Pick your track), learning approach, track comparison, and FAQ. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page".
 */
export interface CoursesPage {
  id: number;
  intro?: {
    pageTitle?: string | null;
    headline?: string | null;
    headlineHighlight?: string | null;
    subtext?: string | null;
  };
  offerings?: {
    eyebrow?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    courses?:
      | {
          variant: 'consultant' | 'end-user';
          title: string;
          description: string;
          /**
           * e.g. "40 Hrs"
           */
          duration?: string | null;
          /**
           * Optional, e.g. Live
           */
          durationSuffix?: string | null;
          /**
           * e.g. "S/4Hana"
           */
          modules?: string | null;
          outcome: string;
          /**
           * Course fee shown on the card and checkout.
           */
          price?: number | null;
          /**
           * Strikethrough price for a discount badge.
           */
          originalPrice?: number | null;
          /**
           * Each line becomes a checklist item on the card.
           */
          highlights: string;
          ctaLabel?: string | null;
          ctaHref?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  learningApproach?: {
    title?: string | null;
    titleHighlight?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    stats?: {
      maxSeats?: {
        value?: string | null;
        label?: string | null;
        description?: string | null;
      };
      mentorLed?: {
        title?: string | null;
        description?: string | null;
      };
      rating?: {
        value?: string | null;
        suffix?: string | null;
      };
    };
  };
  trackComparison?: {
    eyebrow?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    tracks?:
      | {
          badgeVariant: 'consultant' | 'end-user';
          badge: string;
          personaPrefix?: string | null;
          /**
           * e.g. "Builder"
           */
          persona: string;
          personaDescription: string;
          workLabel?: string | null;
          workItems: string;
          toolsLabel?: string | null;
          tools: string;
          outcomeLabel?: string | null;
          outcome: string;
          tags: string;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    eyebrow?: string | null;
    title?: string | null;
    highlight?: string | null;
    helperText?: string | null;
    askLinkLabel?: string | null;
    askLinkHref?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Our Story page (/our-story) — intro + metrics, values, the “We've orchestrated Excellence” pillars, and FAQ. The Mission and Testimonials blocks come from the Home Page global. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story-page".
 */
export interface OurStoryPage {
  id: number;
  intro?: {
    pageTitle?: string | null;
    headline?: string | null;
    headlineHighlight?: string | null;
    headlineSuffix?: string | null;
    subtext?: string | null;
    metrics?:
      | {
          /**
           * e.g. "15,000+"
           */
          value: string;
          label: string;
          icon: 'users' | 'file-badge' | 'building-2' | 'medal' | 'heart' | 'target' | 'award' | 'graduation-cap';
          id?: string | null;
        }[]
      | null;
  };
  values?: {
    title?: string | null;
    titleLine2?: string | null;
    intro?: string | null;
    /**
     * The first card with “Featured” enabled gets the dark style.
     */
    principles?:
      | {
          description: string;
          icon: 'users' | 'file-badge' | 'building-2' | 'medal' | 'heart' | 'target' | 'award' | 'graduation-cap';
          featured?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  excellence?: {
    title?: string | null;
    highlight?: string | null;
    pillars?:
      | {
          /**
           * e.g. "01"
           */
          num: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    eyebrow?: string | null;
    title?: string | null;
    highlight?: string | null;
    helperText?: string | null;
    askLinkLabel?: string | null;
    askLinkHref?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The What's New page (/whats-new) — page title, the update cards, and the newsletter band. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-new-page".
 */
export interface WhatsNewPage {
  id: number;
  intro?: {
    pageTitle?: string | null;
  };
  feed?: {
    /**
     * Drag to reorder. Pinned cards appear first as large blocks; the rest show as the list below.
     */
    updates?:
      | {
          /**
           * When enabled, this card is highlighted at the top and can show an optional button.
           */
          pinned?: boolean | null;
          category: 'admissions' | 'curriculum' | 'placements' | 'notices' | 'events';
          /**
           * e.g. "2 DAYS AGO"
           */
          timeAgo: string;
          badge: 'update' | 'update-navy' | 'notice' | 'alert';
          badgeLabel: string;
          title: string;
          /**
           * Each new line becomes its own paragraph in the card.
           */
          description: string;
          /**
           * Only used on pinned cards. Leave this and the link empty for no button.
           */
          ctaLabel?: string | null;
          /**
           * Page path or URL — e.g. "#pre-footer" or "/courses".
           */
          ctaHref?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  newsletter?: {
    title?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /blog listing page header and sidebar labels. Posts, categories, and recent items come from the Blog Posts collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  intro: {
    pageTitle: string;
    headline: string;
    headlineHighlight: string;
    subtext?: string | null;
  };
  sidebar?: {
    searchPlaceholder?: string | null;
    categoryTitle?: string | null;
    recentTitle?: string | null;
    tagsTitle?: string | null;
    popularTags?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        siteName?: T;
        footerDescription?: T;
        header?:
          | T
          | {
              ctaLabel?: T;
              ctaHref?: T;
            };
      };
  navigation?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              href?: T;
              badge?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        phone?: T;
        phoneHref?: T;
        email?: T;
        emailHref?: T;
        whatsappNumber?: T;
        whatsappLabel?: T;
        whatsappPrefillMessage?: T;
      };
  socialGroup?:
    | T
    | {
        social?:
          | T
          | {
              platform?: T;
              label?: T;
              href?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        exploreTitle?: T;
        exploreLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        courseTitle?: T;
        courseLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        contactTitle?: T;
        copyright?: T;
        craftedText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        titleLine1?: T;
        titleAccent?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
        imageAlt?: T;
      };
  problem?:
    | T
    | {
        headingGray?: T;
        headingNavy?: T;
        items?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
      };
  mission?:
    | T
    | {
        eyebrow?: T;
        headingGray?: T;
        headingNavy?: T;
        roiCard?:
          | T
          | {
              label?: T;
              value?: T;
              suffix?: T;
              description?: T;
              partnersLabel?: T;
            };
        placementCardTop?:
          | T
          | {
              label?: T;
              value?: T;
              suffix?: T;
              description?: T;
            };
        alumniCard?:
          | T
          | {
              body?: T;
              rating?: T;
              ratingSuffix?: T;
              trustedBy?: T;
            };
        placementCardBottom?:
          | T
          | {
              label?: T;
              value?: T;
              suffix?: T;
              description?: T;
            };
        practiceCard?:
          | T
          | {
              label?: T;
              value?: T;
              description?: T;
            };
      };
  instructor?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        photo?: T;
        journeyHeading?: T;
        journeyBody?: T;
        skillsHeading?: T;
        skillsBody?: T;
        featuresLeft?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        featuresRight?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  curriculum?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleLine2?: T;
        titleHighlight?: T;
        titleLine2Suffix?: T;
        modules?:
          | T
          | {
              num?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
        ctaEyebrow?: T;
        ctaTitle?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        items?:
          | T
          | {
              name?: T;
              role?: T;
              initials?: T;
              quote?: T;
              id?: T;
            };
      };
  preFooter?:
    | T
    | {
        badge?: T;
        headingLine1?: T;
        headingLine2?: T;
        description?: T;
        phoneButtonLabel?: T;
        emailButtonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page_select".
 */
export interface CoursesPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        headlineHighlight?: T;
        subtext?: T;
      };
  offerings?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        courses?:
          | T
          | {
              variant?: T;
              title?: T;
              description?: T;
              duration?: T;
              durationSuffix?: T;
              modules?: T;
              outcome?: T;
              price?: T;
              originalPrice?: T;
              highlights?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
            };
      };
  learningApproach?:
    | T
    | {
        title?: T;
        titleHighlight?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
        stats?:
          | T
          | {
              maxSeats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                  };
              mentorLed?:
                | T
                | {
                    title?: T;
                    description?: T;
                  };
              rating?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                  };
            };
      };
  trackComparison?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        tracks?:
          | T
          | {
              badgeVariant?: T;
              badge?: T;
              personaPrefix?: T;
              persona?: T;
              personaDescription?: T;
              workLabel?: T;
              workItems?: T;
              toolsLabel?: T;
              tools?: T;
              outcomeLabel?: T;
              outcome?: T;
              tags?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        helperText?: T;
        askLinkLabel?: T;
        askLinkHref?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story-page_select".
 */
export interface OurStoryPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        headlineHighlight?: T;
        headlineSuffix?: T;
        subtext?: T;
        metrics?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  values?:
    | T
    | {
        title?: T;
        titleLine2?: T;
        intro?: T;
        principles?:
          | T
          | {
              description?: T;
              icon?: T;
              featured?: T;
              id?: T;
            };
      };
  excellence?:
    | T
    | {
        title?: T;
        highlight?: T;
        pillars?:
          | T
          | {
              num?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        helperText?: T;
        askLinkLabel?: T;
        askLinkHref?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-new-page_select".
 */
export interface WhatsNewPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        pageTitle?: T;
      };
  feed?:
    | T
    | {
        updates?:
          | T
          | {
              pinned?: T;
              category?: T;
              timeAgo?: T;
              badge?: T;
              badgeLabel?: T;
              title?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        headlineHighlight?: T;
        subtext?: T;
      };
  sidebar?:
    | T
    | {
        searchPlaceholder?: T;
        categoryTitle?: T;
        recentTitle?: T;
        tagsTitle?: T;
        popularTags?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}