/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'course-details': CourseDetail;
    'workshop-details': WorkshopDetail;
    'blog-posts': BlogPost;
    enrollments: Enrollment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'course-details': CourseDetailsSelect<false> | CourseDetailsSelect<true>;
    'workshop-details': WorkshopDetailsSelect<false> | WorkshopDetailsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'courses-listing': CoursesListing;
    'courses-page': CoursesPage;
    'workshops-page': WorkshopsPage;
    'our-story-page': OurStoryPage;
    'our-team-page': OurTeamPage;
    'whats-new-page': WhatsNewPage;
    'blog-page': BlogPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'courses-listing': CoursesListingSelect<false> | CoursesListingSelect<true>;
    'courses-page': CoursesPageSelect<false> | CoursesPageSelect<true>;
    'workshops-page': WorkshopsPageSelect<false> | WorkshopsPageSelect<true>;
    'our-story-page': OurStoryPageSelect<false> | OurStoryPageSelect<true>;
    'our-team-page': OurTeamPageSelect<false> | OurTeamPageSelect<true>;
    'whats-new-page': WhatsNewPageSelect<false> | WhatsNewPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin accounts that can log in and edit website content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload images here (hero photo, instructor photo, etc.), then pick them on the Home Page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short text describing the image — e.g. “Students learning SAP on laptops”.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Individual course pages at /courses/<slug> (e.g. the Consultant Track and End User Track detail pages). Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-details".
 */
export interface CourseDetail {
  id: number;
  /**
   * Shown in the admin list only.
   */
  name: string;
  /**
   * URL path under /courses/ — e.g. sap-fico-consultant-track.
   */
  slug: string;
  meta: {
    title: string;
    description: string;
  };
  intro: {
    pageTitle: string;
    headline: string;
    headlineHighlight: string;
    subtext?: string | null;
  };
  overview: {
    description: string;
    /**
     * Course fee for checkout.
     */
    price?: number | null;
    originalPrice?: number | null;
    primaryCta?: string | null;
    secondaryCta?: string | null;
    secondaryCtaHref?: string | null;
    moduleCount?: string | null;
    moduleLabel?: string | null;
    moduleBlurb?: string | null;
    metaCards?:
      | {
          icon: 'duration' | 'modules' | 'format' | 'outcome';
          label: string;
          value: string;
          valueSuffix?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  whoIsItFor: {
    eyebrow?: string | null;
    title: string;
    titleHighlight: string;
    audience: string;
    handsOnTitle?: string | null;
    handsOnDescription?: string | null;
    handsOnFeatures: string;
  };
  syllabus?: {
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Optional note shown above the modules list. Leave the text empty to hide it.
     */
    notice?: {
      enabled?: boolean | null;
      text?: string | null;
      /**
       * A phrase from the text above to emphasise (must match exactly).
       */
      highlight?: string | null;
    };
    items?:
      | {
          /**
           * e.g. "01"
           */
          number: string;
          title: string;
          description?: string | null;
          topics: string;
          id?: string | null;
        }[]
      | null;
  };
  footerBlocks: {
    alsoOffered: {
      eyebrow?: string | null;
      title: string;
      href: string;
      ctaLabel?: string | null;
    };
    limitedSeatsCta?: {
      eyebrow?: string | null;
      titleLine1?: string | null;
      titleLine2?: string | null;
      description?: string | null;
      ctaLabel?: string | null;
      ctaHref?: string | null;
    };
  };
  faq?: {
    eyebrow?: string | null;
    title?: string | null;
    highlight?: string | null;
    helperText?: string | null;
    askLinkLabel?: string | null;
    askLinkHref?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual workshop pages at /workshops/<slug>. Listing intro and shared labels live on the Workshops Page global. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-details".
 */
export interface WorkshopDetail {
  id: number;
  /**
   * Shown in the admin list only.
   */
  name: string;
  /**
   * URL path under /workshops/ — e.g. career-pathways-and-success-strategies.
   */
  slug: string;
  /**
   * Lower numbers appear first on the listing.
   */
  sortOrder?: number | null;
  published?: boolean | null;
  /**
   * Short label for the Workshops nav dropdown. Falls back to eyebrow/title if empty.
   */
  navLabel?: string | null;
  meta?: {
    /**
     * Browser tab title. Leave empty to use “{workshop title} | SRR Careers”.
     */
    title?: string | null;
    /**
     * Leave empty to use the card summary.
     */
    description?: string | null;
  };
  card: {
    eyebrow: string;
    title: string;
    /**
     * Short blurb on the /workshops card grid.
     */
    summary: string;
    /**
     * Optional, e.g. "3 hours (including Q&A)". Shown as the sample on cards and detail.
     */
    durationBaseline?: string | null;
  };
  detail: {
    /**
     * Longer intro under the title on the detail page.
     */
    description: string;
    mode?: string | null;
    speaker?: string | null;
    audience?: string | null;
    highlights?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * If set to an existing Course Detail slug, /workshops/{this-slug} renders that course page instead of the workshop template.
     */
    courseDetailSlug?: string | null;
  };
  agenda: {
    /**
     * Pick one layout. Only the matching fields below are used on the site.
     */
    layout: 'modules' | 'sessions' | 'formats' | 'none';
    modules?:
      | {
          title: string;
          /**
           * e.g. "20 mins"
           */
          duration?: string | null;
          id?: string | null;
        }[]
      | null;
    sessions?:
      | {
          label: string;
          /**
           * e.g. "10:00 AM – 1:00 PM"
           */
          time?: string | null;
          modules?:
            | {
                title: string;
                /**
                 * e.g. "20 mins"
                 */
                duration?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    formats?:
      | {
          /**
           * Stable id, e.g. "3hr"
           */
          formatId: string;
          title: string;
          duration: string;
          audience?: string | null;
          note?: string | null;
          modules?:
            | {
                title: string;
                /**
                 * e.g. "20 mins"
                 */
                duration?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles shown on /blog and /blog/<slug>. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * Shown in the admin list only. Also used to auto-generate the URL slug.
   */
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * URL path under /blog/ — auto-generated from Internal name. Unlock to edit manually.
   */
  slug: string;
  meta: {
    title: string;
    description: string;
  };
  content: {
    title: string;
    /**
     * Shown on cards and at the top of the post.
     */
    excerpt: string;
    /**
     * Optional. Leave empty to use an on-brand gradient banner.
     */
    coverImage?: (number | null) | Media;
    author: string;
    authorRole?: string | null;
    publishedDate: string;
    readTime?: string | null;
    category: string;
    featured?: boolean | null;
    tags?: string | null;
  };
  article?: {
    tableOfContents?: string | null;
    body?:
      | (
          | {
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'paragraph';
            }
          | {
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'heading';
            }
          | {
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'quote';
            }
          | {
              items: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'list';
            }
          | {
              image?: (number | null) | Media;
              caption?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'image';
            }
        )[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Checkout + payment records. The Razorpay webhook keeps status in sync; do not edit status by hand unless reconciling.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  name: string;
  email: string;
  mobile: string;
  courseSlug: string;
  /**
   * Snapshot of the course title at checkout time.
   */
  courseName?: string | null;
  planType: 'single' | 'installment';
  status: 'lead' | 'pending' | 'failed' | 'success';
  /**
   * Amount charged for this transaction (whole INR).
   */
  amount: number;
  /**
   * First installment amount (whole INR), if applicable.
   */
  firstInstallmentAmount?: number | null;
  /**
   * Full course price at checkout time (whole INR).
   */
  coursePrice?: number | null;
  currency?: string | null;
  /**
   * Date the (first) payment succeeded.
   */
  paymentDate?: string | null;
  /**
   * Due date for the next installment (one month after payment). Empty for single payments / fully-paid plans.
   */
  nextInstallmentDate?: string | null;
  /**
   * Stable id from step 1. Used as the Google Sheet upsert key.
   */
  leadToken?: string | null;
  /**
   * Razorpay order id (draft_* placeholder until checkout step 2).
   */
  orderId: string;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  pincode?: string | null;
  /**
   * Razorpay payment id.
   */
  paymentId?: string | null;
  /**
   * Populated when a payment fails.
   */
  failureReason?: string | null;
  mailedSuccess?: boolean | null;
  mailedFailed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'course-details';
        value: number | CourseDetail;
      } | null)
    | ({
        relationTo: 'workshop-details';
        value: number | WorkshopDetail;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-details_select".
 */
export interface CourseDetailsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        headlineHighlight?: T;
        subtext?: T;
      };
  overview?:
    | T
    | {
        description?: T;
        price?: T;
        originalPrice?: T;
        primaryCta?: T;
        secondaryCta?: T;
        secondaryCtaHref?: T;
        moduleCount?: T;
        moduleLabel?: T;
        moduleBlurb?: T;
        metaCards?:
          | T
          | {
              icon?: T;
              label?: T;
              value?: T;
              valueSuffix?: T;
              id?: T;
            };
      };
  whoIsItFor?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        audience?: T;
        handsOnTitle?: T;
        handsOnDescription?: T;
        handsOnFeatures?: T;
      };
  syllabus?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        notice?:
          | T
          | {
              enabled?: T;
              text?: T;
              highlight?: T;
            };
        items?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              topics?: T;
              id?: T;
            };
      };
  footerBlocks?:
    | T
    | {
        alsoOffered?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              href?: T;
              ctaLabel?: T;
            };
        limitedSeatsCta?:
          | T
          | {
              eyebrow?: T;
              titleLine1?: T;
              titleLine2?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        helperText?: T;
        askLinkLabel?: T;
        askLinkHref?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-details_select".
 */
export interface WorkshopDetailsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  published?: T;
  navLabel?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  card?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        summary?: T;
        durationBaseline?: T;
      };
  detail?:
    | T
    | {
        description?: T;
        mode?: T;
        speaker?: T;
        audience?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        courseDetailSlug?: T;
      };
  agenda?:
    | T
    | {
        layout?: T;
        modules?:
          | T
          | {
              title?: T;
              duration?: T;
              id?: T;
            };
        sessions?:
          | T
          | {
              label?: T;
              time?: T;
              modules?:
                | T
                | {
                    title?: T;
                    duration?: T;
                    id?: T;
                  };
              id?: T;
            };
        formats?:
          | T
          | {
              formatId?: T;
              title?: T;
              duration?: T;
              audience?: T;
              note?: T;
              modules?:
                | T
                | {
                    title?: T;
                    duration?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  content?:
    | T
    | {
        title?: T;
        excerpt?: T;
        coverImage?: T;
        author?: T;
        authorRole?: T;
        publishedDate?: T;
        readTime?: T;
        category?: T;
        featured?: T;
        tags?: T;
      };
  article?:
    | T
    | {
        tableOfContents?: T;
        body?:
          | T
          | {
              paragraph?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              heading?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              quote?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              list?:
                | T
                | {
                    items?: T;
                    id?: T;
                    blockName?: T;
                  };
              image?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  mobile?: T;
  courseSlug?: T;
  courseName?: T;
  planType?: T;
  status?: T;
  amount?: T;
  firstInstallmentAmount?: T;
  coursePrice?: T;
  currency?: T;
  paymentDate?: T;
  nextInstallmentDate?: T;
  leadToken?: T;
  orderId?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  pincode?: T;
  paymentId?: T;
  failureReason?: T;
  mailedSuccess?: T;
  mailedFailed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide chrome shared on every page — header, navigation, footer, contact details, and social links. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand?: {
    /**
     * Shown next to the logo in the header and footer.
     */
    siteName?: string | null;
    footerDescription?: string | null;
    /**
     * Thin bar above the navbar. Phone & email on the right come from the Contact tab.
     */
    topStrip?: {
      enabled?: boolean | null;
      /**
       * Shown on the left of the header top strip (e.g. Registered with MSME).
       */
      label?: string | null;
    };
    header?: {
      ctaLabel?: string | null;
      ctaHref?: string | null;
    };
  };
  navigation?: {
    items?:
      | {
          label: string;
          href: string;
          badge?: boolean | null;
          /**
           * Optional. Add sub-links to turn this nav item into a hover dropdown (desktop) or expandable accordion (mobile). Leave empty for a flat link. Courses and Workshops dropdowns are driven by their listing pages (Courses Listing / Workshop Detail Pages) — edits there update the nav automatically. Nested “Parent group” + child links work for any other top-level item you configure here.
           */
          children?:
            | {
                label: string;
                /**
                 * Page path (e.g. /courses/sap-fico), # anchor, or URL. For a group parent that is also clickable, set the programme page path.
                 */
                href: string;
                /**
                 * Shows nested links on hover (desktop) / expand (mobile).
                 */
                isGroup?: boolean | null;
                /**
                 * e.g. under SAP FICO → Consultant Track, End User Track.
                 */
                nestedChildren?:
                  | {
                      label: string;
                      href: string;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    phone?: string | null;
    /**
     * Leave blank to auto-build from the number.
     */
    phoneHref?: string | null;
    email?: string | null;
    /**
     * Leave blank to auto-build a mailto link.
     */
    emailHref?: string | null;
    whatsappNumber?: string | null;
    whatsappLabel?: string | null;
    whatsappPrefillMessage?: string | null;
  };
  socialGroup?: {
    social?:
      | {
          platform: 'linkedin' | 'youtube' | 'instagram' | 'whatsapp';
          label: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    exploreTitle?: string | null;
    exploreLinks?:
      | {
          label: string;
          /**
           * Page path or # anchor or URL
           */
          href: string;
          id?: string | null;
        }[]
      | null;
    courseTitle?: string | null;
    courseLinks?:
      | {
          label: string;
          /**
           * Page path or # anchor or URL
           */
          href: string;
          id?: string | null;
        }[]
      | null;
    contactTitle?: string | null;
    copyright?: string | null;
    /**
     * Short trust line in the footer (e.g. MSME / Udyam registration).
     */
    craftedText?: string | null;
    showMsmeLogo?: boolean | null;
    /**
     * Caption under the MSME logo in the footer brand column.
     */
    msmeBadgeLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Everything visitors see on the homepage (srrcareers.in). Open each tab below — changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    badge?: string | null;
    titleLine1?: string | null;
    titleAccent?: string | null;
    primaryCta: {
      label: string;
      /**
       * Page path or URL — e.g. "#courses" or "/courses".
       */
      href: string;
    };
    secondaryCta: {
      label: string;
      /**
       * Page path or URL — e.g. "#courses" or "/courses".
       */
      href: string;
    };
    /**
     * Wide image under the headline. Leave empty to use the default site image.
     */
    image?: (number | null) | Media;
    imageAlt?: string | null;
  };
  problem?: {
    headingGray?: string | null;
    headingNavy?: string | null;
    /**
     * Each row is one concern your visitors might have. Drag to reorder.
     */
    items?:
      | {
          /**
           * Small icon shown above the text.
           */
          icon: 'chat' | 'settings' | 'chart' | 'alert' | 'project' | 'clock';
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  mission?: {
    eyebrow?: string | null;
    headingGray?: string | null;
    headingNavy?: string | null;
    roiCard?: {
      label?: string | null;
      value?: string | null;
      suffix?: string | null;
      description?: string | null;
      partnersLabel?: string | null;
    };
    placementCardTop?: {
      label?: string | null;
      value?: string | null;
      suffix?: string | null;
      description?: string | null;
    };
    alumniCard?: {
      body?: string | null;
      rating?: string | null;
      ratingSuffix?: string | null;
      trustedBy?: string | null;
    };
    placementCardBottom?: {
      label?: string | null;
      value?: string | null;
      suffix?: string | null;
      description?: string | null;
    };
    practiceCard?: {
      label?: string | null;
      value?: string | null;
      description?: string | null;
    };
  };
  instructor?: {
    eyebrow?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    photo?: (number | null) | Media;
    journeyHeading?: string | null;
    journeyBody?: string | null;
    skillsHeading?: string | null;
    skillsBody?: string | null;
    featuresLeft?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    featuresRight?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  curriculum: {
    eyebrow?: string | null;
    titleLine1?: string | null;
    titleLine2?: string | null;
    titleHighlight?: string | null;
    titleLine2Suffix?: string | null;
    /**
     * Optional note shown above the modules list. Leave the text empty to hide it.
     */
    notice?: {
      enabled?: boolean | null;
      text?: string | null;
      /**
       * A phrase from the text above to emphasise (must match exactly).
       */
      highlight?: string | null;
    };
    /**
     * Number, title, and short description for each row.
     */
    modules?:
      | {
          num: string;
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
    ctaEyebrow?: string | null;
    ctaTitle?: string | null;
    cta: {
      label: string;
      /**
       * Page path or URL — e.g. "#courses" or "/courses".
       */
      href: string;
    };
  };
  testimonials?: {
    eyebrow?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    items?:
      | {
          name: string;
          role: string;
          /**
           * 2 letters shown in the avatar circle — e.g. RS
           */
          initials: string;
          quote: string;
          id?: string | null;
        }[]
      | null;
  };
  preFooter?: {
    badge?: string | null;
    headingLine1?: string | null;
    headingLine2?: string | null;
    description?: string | null;
    /**
     * Display only — phone number itself is in Site Settings (coming soon).
     */
    phoneButtonLabel?: string | null;
    emailButtonLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Courses catalogue (/courses) — intro and programme cards. Each card links to a programme page (e.g. SAP FICO) or a course detail. Also drives the Courses nav dropdown. SAP FICO track copy lives on Courses Page; individual course pages under Course Detail Pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-listing".
 */
export interface CoursesListing {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  intro?: {
    pageTitle?: string | null;
    headline?: string | null;
    subtext?: string | null;
  };
  cards?: {
    durationPrefix?: string | null;
    pricePrefix?: string | null;
  };
  programs?:
    | {
        /**
         * Stable id (e.g. sap-fico).
         */
        slug: string;
        sortOrder?: number | null;
        published?: boolean | null;
        /**
         * Courses dropdown label.
         */
        navLabel?: string | null;
        eyebrow: string;
        title: string;
        /**
         * e.g. /courses/sap-fico or /courses/advanced-excel
         */
        href: string;
        summary: string;
        durationLabel?: string | null;
        priceLabel?: string | null;
        /**
         * When on, this programme appears as a parent in the Courses dropdown with the nested links below (e.g. SAP FICO → Consultant / End User).
         */
        isNavGroup?: boolean | null;
        /**
         * Shown under this programme in the Courses dropdown when “Nav group” is on.
         */
        navChildren?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The SAP FICO programme page (/courses/sap-fico) — intro, the two track cards (Pick your track), learning approach, track comparison, and FAQ. The Courses catalogue lives on Courses Listing. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page".
 */
export interface CoursesPage {
  id: number;
  intro?: {
    pageTitle?: string | null;
    headline?: string | null;
    headlineHighlight?: string | null;
    subtext?: string | null;
  };
  offerings?: {
    eyebrow?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    courses?:
      | {
          variant: 'consultant' | 'end-user';
          title: string;
          description: string;
          /**
           * e.g. "40 Hrs"
           */
          duration?: string | null;
          /**
           * Optional, e.g. Live
           */
          durationSuffix?: string | null;
          /**
           * e.g. "S/4Hana"
           */
          modules?: string | null;
          outcome: string;
          price?: number | null;
          originalPrice?: number | null;
          /**
           * Each line becomes a checklist item on the card.
           */
          highlights: string;
          ctaLabel?: string | null;
          ctaHref?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  learningApproach?: {
    title?: string | null;
    titleHighlight?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    stats?: {
      maxSeats?: {
        value?: string | null;
        label?: string | null;
        description?: string | null;
      };
      mentorLed?: {
        title?: string | null;
        description?: string | null;
      };
      rating?: {
        value?: string | null;
        suffix?: string | null;
      };
    };
  };
  trackComparison?: {
    eyebrow?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    tracks?:
      | {
          badgeVariant: 'consultant' | 'end-user';
          badge: string;
          personaPrefix?: string | null;
          /**
           * e.g. "Builder"
           */
          persona: string;
          personaDescription: string;
          workLabel?: string | null;
          workItems: string;
          toolsLabel?: string | null;
          tools: string;
          outcomeLabel?: string | null;
          outcome: string;
          tags: string;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    eyebrow?: string | null;
    title?: string | null;
    highlight?: string | null;
    helperText?: string | null;
    askLinkLabel?: string | null;
    askLinkHref?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Workshops listing (/workshops) — intro, shared duration/pricing labels, card labels, and chrome for every workshop detail page. Individual workshops are edited under Workshop Detail Pages. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops-page".
 */
export interface WorkshopsPage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  intro?: {
    pageTitle?: string | null;
    headline?: string | null;
    /**
     * Use {{duration}} where the duration label should appear (lowercased). Example: …are both {{duration}} for your institution…
     */
    subtext?: string | null;
  };
  shared?: {
    durationLabel?: string | null;
    pricingLabel?: string | null;
    durationNote?: string | null;
    pricingNote?: string | null;
  };
  cards?: {
    durationPrefix?: string | null;
    pricePrefix?: string | null;
    /**
     * Shown after the duration value when a workshop has a sample baseline, e.g. “Customisable · sample 3 hours”.
     */
    samplePrefix?: string | null;
  };
  detail?: {
    metaDurationLabel?: string | null;
    metaPriceLabel?: string | null;
    metaModeLabel?: string | null;
    metaAudienceLabel?: string | null;
    metaSpeakerLabel?: string | null;
    pricingEyebrow?: string | null;
    pricingHeadline?: string | null;
    /**
     * Appended before the workshop’s duration baseline on the detail page.
     */
    sampleAgendaPrefix?: string | null;
    highlightsHeading?: string | null;
    agendaEyebrow?: string | null;
    agendaTitleModules?: string | null;
    agendaTitleSessions?: string | null;
    agendaTitleFormats?: string | null;
    formatAudienceLabel?: string | null;
    backCtaLabel?: string | null;
    backCtaHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Our Story page (/our-story) — intro + metrics, values, the “We've orchestrated Excellence” pillars, and FAQ. The Mission and Testimonials blocks come from the Home Page global. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story-page".
 */
export interface OurStoryPage {
  id: number;
  intro?: {
    pageTitle?: string | null;
    headline?: string | null;
    headlineHighlight?: string | null;
    headlineSuffix?: string | null;
    subtext?: string | null;
    metrics?:
      | {
          /**
           * e.g. "15,000+"
           */
          value: string;
          label: string;
          icon: 'users' | 'file-badge' | 'building-2' | 'medal' | 'heart' | 'target' | 'award' | 'graduation-cap';
          id?: string | null;
        }[]
      | null;
  };
  values?: {
    title?: string | null;
    titleLine2?: string | null;
    intro?: string | null;
    /**
     * The first card with “Featured” enabled gets the dark style.
     */
    principles?:
      | {
          description: string;
          icon: 'users' | 'file-badge' | 'building-2' | 'medal' | 'heart' | 'target' | 'award' | 'graduation-cap';
          featured?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  excellence?: {
    title?: string | null;
    highlight?: string | null;
    pillars?:
      | {
          /**
           * e.g. "01"
           */
          num: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    eyebrow?: string | null;
    title?: string | null;
    highlight?: string | null;
    helperText?: string | null;
    askLinkLabel?: string | null;
    askLinkHref?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Our Team page (/our-team) — intro copy and faculty profiles. Click a member to edit card + profile popup (bio, workshops, photo). Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-team-page".
 */
export interface OurTeamPage {
  id: number;
  intro?: {
    pageTitle?: string | null;
    headline?: string | null;
    subtext?: string | null;
  };
  membersSection?: {
    viewProfileLabel?: string | null;
    workshopsHeading?: string | null;
    /**
     * Drag to reorder. Each row is a card on the page; Bio + Workshops appear in the profile popup when someone clicks the card. Upload a square headshot (≈480×480), or leave empty to use the fallback image path.
     */
    members?:
      | {
          /**
           * e.g. "kumar-arun"
           */
          slug: string;
          name: string;
          /**
           * Shown on the card and as the badge in the profile popup (e.g. "SAP FICO Expert", "CA").
           */
          credential: string;
          /**
           * Used on the card and in the popup. Square JPEG/PNG, ideally 480×480. Leave empty to keep the fallback path below.
           */
          photo?: (number | null) | Media;
          /**
           * Public path used when no CMS photo is uploaded, e.g. /images/team/kumar-arun.jpg
           */
          fallbackImagePath?: string | null;
          placeholderGradient:
            | 'from-brand-lavender via-brand-purple-light to-brand-purple'
            | 'from-brand-purple-light via-brand-purple to-brand-purple-deep'
            | 'from-brand-lavender via-brand-purple to-brand-purple-light'
            | 'from-brand-purple-deep via-brand-purple to-brand-purple-light';
          /**
           * Main body copy inside the profile popup. Add one row per paragraph.
           */
          bio?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Optional list at the bottom of the popup. Leave empty to hide that block.
           */
          workshops?:
            | {
                title: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The What's New page (/whats-new) — page title, the update cards, and the newsletter band. Changes go live after you click Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-new-page".
 */
export interface WhatsNewPage {
  id: number;
  intro?: {
    pageTitle?: string | null;
  };
  feed?: {
    /**
     * Drag to reorder. Pinned cards appear first as large blocks; the rest show as the list below.
     */
    updates?:
      | {
          /**
           * When enabled, this card is highlighted at the top and can show an optional button.
           */
          pinned?: boolean | null;
          category: 'admissions' | 'curriculum' | 'placements' | 'notices' | 'events';
          /**
           * e.g. "2 DAYS AGO"
           */
          timeAgo: string;
          badge: 'update' | 'update-navy' | 'notice' | 'alert';
          badgeLabel: string;
          title: string;
          /**
           * Each new line becomes its own paragraph in the card.
           */
          description: string;
          /**
           * Only used on pinned cards. Leave this and the link empty for no button.
           */
          ctaLabel?: string | null;
          /**
           * Page path or URL — e.g. "#pre-footer" or "/courses".
           */
          ctaHref?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  newsletter?: {
    title?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /blog listing page header and sidebar labels. Posts, categories, and recent items come from the Blog Posts collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  intro: {
    pageTitle: string;
    headline: string;
    headlineHighlight: string;
    subtext?: string | null;
  };
  sidebar?: {
    searchPlaceholder?: string | null;
    categoryTitle?: string | null;
    recentTitle?: string | null;
    tagsTitle?: string | null;
    popularTags?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        siteName?: T;
        footerDescription?: T;
        topStrip?:
          | T
          | {
              enabled?: T;
              label?: T;
            };
        header?:
          | T
          | {
              ctaLabel?: T;
              ctaHref?: T;
            };
      };
  navigation?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              href?: T;
              badge?: T;
              children?:
                | T
                | {
                    label?: T;
                    href?: T;
                    isGroup?: T;
                    nestedChildren?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
      };
  contact?:
    | T
    | {
        phone?: T;
        phoneHref?: T;
        email?: T;
        emailHref?: T;
        whatsappNumber?: T;
        whatsappLabel?: T;
        whatsappPrefillMessage?: T;
      };
  socialGroup?:
    | T
    | {
        social?:
          | T
          | {
              platform?: T;
              label?: T;
              href?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        exploreTitle?: T;
        exploreLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        courseTitle?: T;
        courseLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        contactTitle?: T;
        copyright?: T;
        craftedText?: T;
        showMsmeLogo?: T;
        msmeBadgeLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        titleLine1?: T;
        titleAccent?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
        imageAlt?: T;
      };
  problem?:
    | T
    | {
        headingGray?: T;
        headingNavy?: T;
        items?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
      };
  mission?:
    | T
    | {
        eyebrow?: T;
        headingGray?: T;
        headingNavy?: T;
        roiCard?:
          | T
          | {
              label?: T;
              value?: T;
              suffix?: T;
              description?: T;
              partnersLabel?: T;
            };
        placementCardTop?:
          | T
          | {
              label?: T;
              value?: T;
              suffix?: T;
              description?: T;
            };
        alumniCard?:
          | T
          | {
              body?: T;
              rating?: T;
              ratingSuffix?: T;
              trustedBy?: T;
            };
        placementCardBottom?:
          | T
          | {
              label?: T;
              value?: T;
              suffix?: T;
              description?: T;
            };
        practiceCard?:
          | T
          | {
              label?: T;
              value?: T;
              description?: T;
            };
      };
  instructor?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        photo?: T;
        journeyHeading?: T;
        journeyBody?: T;
        skillsHeading?: T;
        skillsBody?: T;
        featuresLeft?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        featuresRight?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  curriculum?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleLine2?: T;
        titleHighlight?: T;
        titleLine2Suffix?: T;
        notice?:
          | T
          | {
              enabled?: T;
              text?: T;
              highlight?: T;
            };
        modules?:
          | T
          | {
              num?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
        ctaEyebrow?: T;
        ctaTitle?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        items?:
          | T
          | {
              name?: T;
              role?: T;
              initials?: T;
              quote?: T;
              id?: T;
            };
      };
  preFooter?:
    | T
    | {
        badge?: T;
        headingLine1?: T;
        headingLine2?: T;
        description?: T;
        phoneButtonLabel?: T;
        emailButtonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-listing_select".
 */
export interface CoursesListingSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        subtext?: T;
      };
  cards?:
    | T
    | {
        durationPrefix?: T;
        pricePrefix?: T;
      };
  programs?:
    | T
    | {
        slug?: T;
        sortOrder?: T;
        published?: T;
        navLabel?: T;
        eyebrow?: T;
        title?: T;
        href?: T;
        summary?: T;
        durationLabel?: T;
        priceLabel?: T;
        isNavGroup?: T;
        navChildren?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page_select".
 */
export interface CoursesPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        headlineHighlight?: T;
        subtext?: T;
      };
  offerings?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        courses?:
          | T
          | {
              variant?: T;
              title?: T;
              description?: T;
              duration?: T;
              durationSuffix?: T;
              modules?: T;
              outcome?: T;
              price?: T;
              originalPrice?: T;
              highlights?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
            };
      };
  learningApproach?:
    | T
    | {
        title?: T;
        titleHighlight?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
        stats?:
          | T
          | {
              maxSeats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                  };
              mentorLed?:
                | T
                | {
                    title?: T;
                    description?: T;
                  };
              rating?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                  };
            };
      };
  trackComparison?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        tracks?:
          | T
          | {
              badgeVariant?: T;
              badge?: T;
              personaPrefix?: T;
              persona?: T;
              personaDescription?: T;
              workLabel?: T;
              workItems?: T;
              toolsLabel?: T;
              tools?: T;
              outcomeLabel?: T;
              outcome?: T;
              tags?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        helperText?: T;
        askLinkLabel?: T;
        askLinkHref?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops-page_select".
 */
export interface WorkshopsPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        subtext?: T;
      };
  shared?:
    | T
    | {
        durationLabel?: T;
        pricingLabel?: T;
        durationNote?: T;
        pricingNote?: T;
      };
  cards?:
    | T
    | {
        durationPrefix?: T;
        pricePrefix?: T;
        samplePrefix?: T;
      };
  detail?:
    | T
    | {
        metaDurationLabel?: T;
        metaPriceLabel?: T;
        metaModeLabel?: T;
        metaAudienceLabel?: T;
        metaSpeakerLabel?: T;
        pricingEyebrow?: T;
        pricingHeadline?: T;
        sampleAgendaPrefix?: T;
        highlightsHeading?: T;
        agendaEyebrow?: T;
        agendaTitleModules?: T;
        agendaTitleSessions?: T;
        agendaTitleFormats?: T;
        formatAudienceLabel?: T;
        backCtaLabel?: T;
        backCtaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story-page_select".
 */
export interface OurStoryPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        headlineHighlight?: T;
        headlineSuffix?: T;
        subtext?: T;
        metrics?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  values?:
    | T
    | {
        title?: T;
        titleLine2?: T;
        intro?: T;
        principles?:
          | T
          | {
              description?: T;
              icon?: T;
              featured?: T;
              id?: T;
            };
      };
  excellence?:
    | T
    | {
        title?: T;
        highlight?: T;
        pillars?:
          | T
          | {
              num?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        helperText?: T;
        askLinkLabel?: T;
        askLinkHref?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-team-page_select".
 */
export interface OurTeamPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        subtext?: T;
      };
  membersSection?:
    | T
    | {
        viewProfileLabel?: T;
        workshopsHeading?: T;
        members?:
          | T
          | {
              slug?: T;
              name?: T;
              credential?: T;
              photo?: T;
              fallbackImagePath?: T;
              placeholderGradient?: T;
              bio?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              workshops?:
                | T
                | {
                    title?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-new-page_select".
 */
export interface WhatsNewPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        pageTitle?: T;
      };
  feed?:
    | T
    | {
        updates?:
          | T
          | {
              pinned?: T;
              category?: T;
              timeAgo?: T;
              badge?: T;
              badgeLabel?: T;
              title?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        pageTitle?: T;
        headline?: T;
        headlineHighlight?: T;
        subtext?: T;
      };
  sidebar?:
    | T
    | {
        searchPlaceholder?: T;
        categoryTitle?: T;
        recentTitle?: T;
        tagsTitle?: T;
        popularTags?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}